name: Documentation

env:
  ACTIONS_RUNNER_DEBUG: true

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    # Build the HTML documentation
    - name: Doxygen Action
      uses: mattnotmitt/doxygen-action@v1.3.1
      with:
          doxyfile-path: 'mod_1/hw_4/Doxyfile'
          working-directory: '.'

    # store the doc files
    - name: Upload Output Directory
      uses: actions/upload-artifact@v2
      with:
        name: doc-files
        path: 'mod_1/hw_4/doc'
        retention-days: 1

  copy:
    runs-on: ubuntu-20.04
    needs: build

    steps:
      # checkout the gh-pages branch
      - uses: actions/checkout@v2
        with:
          ref: gh-pages

      # download the doc files, most of which are generated above
      - name: Download Output Directory
        uses: actions/download-artifact@v2
        with:
          name: doc-files
          path: 'mod_1/hw_4/doc'

      # add, commit and push to gh-pages
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Dmitriy Rybalkin
          author_email: dmitriy.rybalkin@gmail.com
          message: 'Update docs'
          branch: gh-pages
          add: '["mod_1/hw_4/doc/html/*"]'